# Configuration Settings for C94-M8P device / Holybro F9P

debug: 1                    # Range 0-4 (0 means no debug statements will print)

save:
  mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver 
                            # Manager, Antenna, and Logging Configuration
  device: 4                 # Save to EEPROM

device: /dev/ttyACM0
#frame_id: gps              # now in launch file
rate: 4                     # in Hz
nav_rate: 4                 # [# of measurement cycles], recommended 1 Hz, may 
                            # be either 5 Hz (Dual constellation) or 
                            # 8 Hz (GPS only)
dynamic_model: automotive   # automotive Used for applications with equivalent dynamics to those of a passenger car. Low vertical acceleration assumed 

fix_mode: auto
enable_ppp: false           # Not supported by C94-M8P
dr_limit: 0

uart1:
  baudrate: 19200           # C94-M8P specific
  in: 32                    # RTCM 3
  out: 0                    # No UART out for rover

# TMODE3 Config
tmode3: 0                   # Disabled

gnss:
  galileo: true             # EU
  glonass: true             # Supported by C94-M8P # Russia
  beidou: true              # Supported by C94-M8P # China
  qzss: false               # Supported by C94-M8P # Japan / SE Asia / Pacific Only
  # GPS USA is set true by default

dgnss_mode: 3               # Fixed mode

inf: 
  all: true                   # Whether to display all INF messages in console

# Enable u-blox message publishers
publish:
  all: true
  aid:
    hui: false

  nav:
    posecef: false
